version: '3.8'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - api

  db:
    image: postgres
    restart: always
    # TODO: Create environment variables for things
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "notes"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/.cppath
      - ./resources/:/usr/src/app/resources
      - ./src/:/usr/src/app/src
      - ./dev/:/usr/src/app/dev
      - ./test/:/usr/src/app/test
    ports:
      - "41985:41985"
    environment:
      - VIRTUAL_HOST=api
      - VIRTUAL_PORT=3000
